### ISSUE TITLE
PERL Library called CheckLib already exists

### ISSUE THREAD

**Issue by annakrystalli** [checklib/checklib#20]
**What is it we need to talk about?**

It appears that there already exists a PERL library called  [CheckLib](https://metacpan.org/pod/Devel::CheckLib). To avoid confusion and conflict, what do people think of changing our name to `chklib`?

**Definition of Done**
What do we need to accomplish to consider this discussion complete? Ex.
- [x] Decide whether sharing a name with a PERL library is ok
- [x] If not decide on a new name

Would be great to get feedback from @checklib/devs folks

**Comment by jmgate** [comment]
I wouldn't worry about changing the name.  The versions of CheckLib that exist on GitHub are all called Devel-CheckLib or perl-devel-CheckLib or things along those lines.

**Comment by annakrystalli** [comment]
OK great. Thanks for the feedback. `checklib` it is! 🎉
